# Generated by Django 2.1.7 on 2019-04-07 12:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('ContactNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Address', models.CharField(max_length=264)),
                ('Age', models.IntegerField()),
                ('Type', models.CharField(choices=[('driver', 'Driver'), ('user', 'User')], default='user', max_length=6)),
                ('RefName1', models.CharField(max_length=264)),
                ('RefContactNo1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('RefName2', models.CharField(max_length=264)),
                ('RefContactNo2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('RefName3', models.CharField(max_length=264)),
                ('RefContactNo3', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('RefName4', models.CharField(max_length=264)),
                ('RefContactNo4', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('RefName5', models.CharField(max_length=264)),
                ('RefContactNo5', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Accuracy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
