# Generated by Django 2.1.7 on 2019-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190409_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=264, verbose_name='Nameee'),
        ),
    ]
