# Generated by Django 2.1.7 on 2019-04-08 19:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190409_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ContactNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=264, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo3',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo4',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefContactNo5',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Emergency Contact Number-5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefName1',
            field=models.CharField(max_length=264, verbose_name='Emergency Contact Name-1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefName2',
            field=models.CharField(max_length=264, verbose_name='Emergency Contact Name-2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefName3',
            field=models.CharField(max_length=264, verbose_name='Emergency Contact Name-3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefName4',
            field=models.CharField(max_length=264, verbose_name='Emergency Contact Name-4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RefName5',
            field=models.CharField(max_length=264, verbose_name='Emergency Contact Name-5'),
        ),
    ]
