# Generated by Django 2.1.7 on 2019-04-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190409_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_sleeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_trips',
            field=models.IntegerField(default=0),
        ),
    ]
